### ISSUE TITLE
知乎登陆错误

### ISSUE THREAD

**Issue by jimmy-walker** [CharlesPikachu/DecryptLogin#13]
邮箱和密码是正确的，但是就是返回错误信息。是不是被知乎官方给屏蔽了？
Input the Verification Code:5UDK
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jimmy\Anaconda3\envs\pyvisual36\lib\site-packages\DecryptLogin\platforms\zhihu.py", line 560, in login
    raise RuntimeError(res_json.get('error').get('message'))
RuntimeError: 该邮箱尚未注册知乎

**Comment by CharlesPikachu** [comment]
用户名现在只支持手机号。因为没用邮箱注册过，所以没考虑是邮箱的情况....
后面更新的时候我会考虑这个情况的
