### ISSUE TITLE
bil

### ISSUE THREAD

**Issue by Asp-fresh** [CharlesPikachu/DecryptLogin#18]
Traceback (most recent call last):
  File "downloadUserVideos.py", line 173, in <module>
    bili.run()
  File "downloadUserVideos.py", line 42, in run
    self.__downloadVideos(userid)
  File "downloadUserVideos.py", line 100, in __downloadVideos
    if 'dash' in res_json['data']:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Asp-fresh** [comment]
通过测试，下载20个小视频未出现错误
