### ISSUE TITLE
知乎登录报错

### ISSUE THREAD

**Issue by igeology** [CharlesPikachu/DecryptLogin#4]
Traceback (most recent call last):
  File "D:/Python_study/ZhihuSpider/test.py", line 600, in <module>
    zhihu().login('****', '****')
  File "D:/Python_study/ZhihuSpider/test.py", line 559, in login
    data = js.call('Q', urlencode(data))
  File "D:\Python_study\ZhihuSpider\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "D:\Python_study\ZhihuSpider\venv\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "D:\Python_study\ZhihuSpider\venv\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\Python_study\ZhihuSpider\venv\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\Python_study\ZhihuSpider\venv\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "D:\Python_study\ZhihuSpider\venv\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: TypeError: base64 is not a function

**Comment by CharlesPikachu** [comment]
You can refer [https://stackoverflow.com/questions/14573001/nodejs-how-to-decode-base64-encoded-string-back-to-binary](url) for solution

你版本太低的原因，解决方案在链接里有。后面的版本我会做更新
