### ISSUE TITLE
知乎输入验证码失败

### ISSUE THREAD

**Issue by 501938568** [CharlesPikachu/DecryptLogin#45]
错误信息：
D:\python\python.exe C:/Users/Administrator/AppData/Roaming/JetBrains/PyCharm2020.2/scratches/scratch_2.py
Input the captcha:UE9y

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\JetBrains\PyCharm2020.2\scratches\scratch_2.py", line 5, in <module>
    infos_return, session = lg.zhihu(username='17730222305', password='zyh123456')
  File "D:\python\lib\site-packages\DecryptLogin\platforms\zhihu.py", line 542, in login
    data = js.call('encrypt', urlencode(data))
  File "D:\python\lib\site-packages\execjs\_abstract_runtime_context.py", line 37, in call
    return self._call(name, *args)
  File "D:\python\lib\site-packages\execjs\_external_runtime.py", line 92, in _call
    return self._eval("{identifier}.apply(this, {args})".format(identifier=identifier, args=args))
  File "D:\python\lib\site-packages\execjs\_external_runtime.py", line 78, in _eval
    return self.exec_(code)
  File "D:\python\lib\site-packages\execjs\_abstract_runtime_context.py", line 18, in exec_
    return self._exec_(source)
  File "D:\python\lib\site-packages\execjs\_external_runtime.py", line 88, in _exec_
    return self._extract_result(output)
  File "D:\python\lib\site-packages\execjs\_external_runtime.py", line 167, in _extract_result
    raise ProgramError(value)
execjs._exceptions.ProgramError: SyntaxError: 缺少标识符

**Comment by CharlesPikachu** [comment]
仔细看文档，需要安装一下nodejs
