### ISSUE TITLE
请问网易云音乐的接口失效了吗？

### ISSUE THREAD

**Issue by mrwanghaoyu** [CharlesPikachu/DecryptLogin#83]
你好，我今天试了一下网易云接口，不知道为何无法登录，username传入的是手机号，我填写issue时把username和password防止泄露改成*了，在运行的时候是对的。手动在网页登陆的时候是没问题的。
我又把music163改为bilibili试了一下，是没有问题的。谢谢！

```
from DecryptLogin import login

def imitatelogin(username, password):
    lg = login.Login()
    infos_return, session = lg.music163(username, password)

imitatelogin('******', '******')
```
这是报错。
```
Traceback (most recent call last):
  File "E:\网易云音乐.py", line 7, in <module>
    imitatelogin('*****', '*****')
  File "E:\网易云音乐.py", line 5, in imitatelogin
    infos_return, session = lg.music163(username, password)
  File "D:\Python\Python39\lib\site-packages\DecryptLogin\modules\core\music163.py", line 167, in login
    return selected_api.login(**args)
  File "D:\Python\Python39\lib\site-packages\DecryptLogin\modules\core\music163.py", line 94, in login
    raise RuntimeError(response_json.get('msg')) if 'msg' in response_json else RuntimeError(response_json.get('message'))
RuntimeError: 当前登录失败，请稍后再试
```

**Comment by CharlesPikachu** [comment]
我这边测试也报错，可能因为接口变了，我刚刚试了网页端登录发现需要滑块验证码了

**Comment by CharlesPikachu** [comment]
我刚刚更新了一版DecryptLogin，支持网易云音乐的扫码登录，可以作为临时的解决方案，PC端的我有空再看看吧
