### ISSUE TITLE
[BUG]京东二维码登陆调用报错

### ISSUE THREAD

**Issue by PaPaB1** [CharlesPikachu/DecryptLogin#88]
**Environment (使用环境)**
  - Operating system (操作系统):  mac os
  - Python version (Python版本):  3.11.0

**Question description (问题描述)**
```
You can visit https://github.com/CharlesPikachu/DecryptLogin for more details.
Traceback (most recent call last):
  File "Documents/PythonTest/Test001.py", line 4, in <module>
    infos_return, session = lg.jingdong('', '', 'scanqr')
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/DecryptLogin/modules/core/jingdong.py", line 128, in login
    return selected_api.login(**args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/DecryptLogin/modules/core/jingdong.py", line 51, in login
    showImage(qrcode_path)
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/DecryptLogin/modules/utils/misc.py", line 20, in showImage
    img.show()
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/Image.py", line 2407, in show
    _show(self, title=title)
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/Image.py", line 3411, in _show
    ImageShow.show(image, **options)
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/ImageShow.py", line 62, in show
    if viewer.show(image, title=title, **options):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/ImageShow.py", line 86, in show
    return self.show_image(image, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/ImageShow.py", line 112, in show_image
    return self.show_file(self.save_image(image), **options)
                          ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/ImageShow.py", line 108, in save_image
    return image._dump(format=self.get_format(image), **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/Image.py", line 621, in _dump
    self.save(filename, format, **options)
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/Image.py", line 2353, in save
    save_handler(self, fp, filename)
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/PngImagePlugin.py", line 1218, in _save_all
    _save(im, fp, filename, save_all=True)
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/PngImagePlugin.py", line 1395, in _save
    _write_multiple_frames(im, fp, chunk, rawmode, default_image, append_images)
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/PngImagePlugin.py", line 1113, in _write_multiple_frames
    im_frame = im_frame.convert(rawmode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yangwei/Documents/PythonTest/venv/lib/python3.11/site-packages/PIL/Image.py", line 1063, in convert
    im = self.im.convert(mode, dither)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: conversion not supported
```

**Screenshot (报错截图)**
<img width="478" alt="image" src="https://user-images.githubusercontent.com/113686153/204131928-b4c8b027-e00d-4d95-a38c-d01d13fd3cae.png">

**Advice (修复建议)**
貌似图片解析错误

**Comment by hsyysy** [comment]
我发现直接用PIL的Image库打开本地的qrcode.png也是一样的错误

**Comment by xiaoyunjie** [comment]
@PaPaB1 此问题你解决了么

**Comment by xiaoyunjie** [comment]
@PaPaB1  pip3 install Pillow==8.4.0 降低Pillow版本可以解决此问题
