### ISSUE TITLE
[BUG]无法登陆知乎

### ISSUE THREAD

**Issue by Liuxc2005** [CharlesPikachu/DecryptLogin#89]
D:\test>python yanxuan.py
Welcome to use DecryptLogin!
You can visit https://github.com/CharlesPikachu/DecryptLogin for more details.
Welcome to use DecryptLogin!
You can visit https://github.com/CharlesPikachu/DecryptLogin for more details.
Traceback (most recent call last):
  File "yanxuan.py", line 8, in <module>
    infos_return, session = zhihu.login(' ', '  ', mode='pc')
  File "C:\Program Files\python\lib\site-packages\DecryptLogin\modules\clients\baseclient.py", line 44, in login
    self.infos_return, self.session = api(username, password, mode, crack_captcha_func, **kwargs)
  File "C:\Program Files\python\lib\site-packages\DecryptLogin\modules\core\zhihu.py", line 675, in login
    return selected_api.login(**args)
  File "C:\Program Files\python\lib\site-packages\DecryptLogin\modules\core\zhihu.py", line 498, in login
    removeImage(captcha_path)
UnboundLocalError: local variable 'captcha_path' referenced before assignment

**Comment by WuJinfeng0715** [comment]
me, too. Do you solve this problem?
